# For more information: https://laravel.com/docs/sail
services:
    laravel.test:
        container_name: aod-site-app
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: aod-site/app
        ports:
            - '${APP_PORT:-8080}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - tracker_site_bridge
networks:
    tracker_site_bridge:
        name: tracker_site_bridge
        external: true
